name: Add all issues to regelrett project

on:
  issues:
    types:
      - opened

jobs:
  add-to-project:
    name: Add issue to project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@v1.0.2
        with:
          project-url: https://github.com/orgs/kartverket/projects/16
          github-token: ${{ secrets.PAT_TOKEN }}