name: Build and deploy
on:
  workflow_dispatch:
    inputs:
      commit_sha:
        description: 'Commit hash to deploy'
        default: ''
        type: string
  pull_request:
    branches:
      - main
  push:
    paths-ignore:
      - .sikkerhet**
      - compose.yaml
      - README**
    branches:
      - main

permissions:
  id-token: write
  contents: write

env:
  PROJECT_ID: spire-regelrett-0x54
  REGION: europe-north1
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  RR_DATABASE_HOST: regelrett-db:5432
  RR_DATABASE_NAME: regelrett
  RR_SCHEMA_SIKKERHETSKONTROLLER_WEBHOOK_ID: "ach2vlnWcdxY8Cl3k"
  RR_SCHEMA_DRIFTSKONTINUITET_WEBHOOK_ID: "achCxVfK6DaWMhchX"

jobs:
  build:
    name: Build and push docker image
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    outputs:
      image: ${{ steps.setOutput.outputs.image }}
    steps:
      - name: Checkout code
        if: ${{ !(github.event_name == 'workflow_dispatch' && inputs.commit_sha == '') }}
        uses: actions/checkout@v4

      - name: Checkout code
        if: ${{ (github.event_name == 'workflow_dispatch' && inputs.commit_sha == '') }}
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Checkout specific commit
        if: ${{ github.event_name == 'workflow_dispatch' && inputs.commit_sha != '' }}
        run: git checkout ${{ github.event.inputs.commit_sha }}

      - name: Set tag
        id: set-tag
        env:
          BRANCH: ${{ github.ref_name }}
        run: |
          if [[ "$BRANCH" == "main" || "$BRANCH" == "master" ]]; then
            echo "image_tag=latest" >> $GITHUB_OUTPUT
          else
            echo "image_tag=prebuild-temp" >> $GITHUB_OUTPUT
          fi

      - name: Login to Github Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=sha,format=long
            type=raw,value=${{ steps.set-tag.outputs.image_tag }}

      - name: Build docker and push
        id: build-docker
        uses: docker/build-push-action@v6
        with:
          push: ${{ !github.event.pull_request.draft }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Set output with build values
        id: setOutput
        run: |
          echo "image=${{ env.IMAGE_NAME }}@${{ steps.build-docker.outputs.digest }}" >> $GITHUB_OUTPUT

  pharos:
    name: Run Pharos
    needs: build
    permissions:
      actions: read
      packages: read
      contents: read
      security-events: write
    runs-on: ubuntu-latest
    steps:
      - name: "Run Pharos"
        uses: kartverket/pharos@7cff320db83b679cce0569f1e171a039f78f72de # v0.2.1
        with:
          image_url: ${{ env.REGISTRY }}/${{ needs.build.outputs.image }}

  deploy-gcp:
    name: Build and deploy to GCP
    # if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ env.PROJECT_ID }}

      - name: Set repository name
        run: echo "IMAGE_NAME=$(echo '${{ github.repository }}' | cut -d'/' -f2)" >> $GITHUB_ENV

      - name: Set Docker image URL
        run: echo "IMAGE_URL=${{ env.REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/ghcr/${{ needs.build.outputs.image }}" >> $GITHUB_ENV

      - name: Debug env variables
        run: |
          echo "IMAGE_NAME is: ${{ env.IMAGE_NAME }}"
          echo "IMAGE_URL IS: ${{ env.IMAGE_URL }}"


      - name: Authenticate to Google Cloud
        id: auth
        uses: "google-github-actions/auth@v2"
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ env.PROJECT_ID }}

      - name: SSH into VM and deploy container
        run: |
          gcloud compute ssh regelrett-backend-vm --zone ${{ env.REGION }}-b --project ${{ secrets.GCP_PROJECT_ID }} --command "
            sudo gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev --quiet &&
            sudo docker stop $(sudo docker ps -a -q) || true &&
            sudo docker rm $(sudo docker ps -a -q) || true &&
            sudo docker network rm container_network || true &&
            sudo docker image prune -f || true &&
            sudo docker network create container_network &&
            sudo docker run --name regelrett-db --network container_network  -it \
              -e POSTGRES_PASSWORD=pwd \
              -e POSTGRES_USER=postgres \
              -e POSTGRES_DB=regelrett \
              -p 5432:5432 -d postgres:15.4
            sudo docker pull '${{ env.IMAGE_URL }}' &&
            sudo docker stop '${{ env.IMAGE_NAME }}' || true &&
            sudo docker rm '${{ env.IMAGE_NAME }}' || true &&
            sudo docker run -d --name '${{ env.IMAGE_NAME }}' --network container_network -p 3000:3000 \
              -e RR_SERVER_HTTP_PORT=3000 \
              -e RR_OAUTH_CLIENT_ID=${{ secrets.ENTRA_CLIENT_ID }} \
              -e RR_OAUTH_TENANT_ID=${{ secrets.ENTRA_TENANT_ID }} \
              -e RR_OAUTH_CLIENT_SECRET=${{ secrets.ENTRA_CLIENT_SECRET }}  \
              -e RR_OAUTH_SUPER_USER_GROUP_ID=${{secrets.SUPER_USER_GROUP_ID}} \
              -e RR_DATABASE_HOST='${{ env.RR_DATABASE_HOST }}' \
              -e RR_DATABASE_NAME='${{ env.RR_DATABASE_NAME }}' \
              -e RR_SCHEMA_SIKKERHETSKONTROLLER_WEBHOOK_ID=${{ env.RR_SCHEMA_SIKKERHETSKONTROLLER_WEBHOOK_ID }} \
              -e RR_SCHEMA_DRIFTSKONTINUITET_WEBHOOK_ID=${{ env.RR_SCHEMA_DRIFTSKONTINUITET_WEBHOOK_ID }} \
              -e RR_SCHEMA_SIKKERHETSKONTROLLER_WEBHOOK_SECRET=${{ secrets.SIKKERHETSKONTROLLER_WEBHOOK_SECRET_GCP }} \
              -e RR_SCHEMA_DRIFTSKONTINUITET_WEBHOOK_SECRET=${{ secrets.DRIFTSKONTINUITET_WEBHOOK_SECRET_GCP }} \
              -e RR_SCHEMA_SIKKERHETSKONTROLLER_AIRTABLE_ACCESS_TOKEN=${{ secrets.AIRTABLE_ACCESS_TOKEN }} \
              -e RR_SCHEMA_DRIFTSKONTINUITET_AIRTABLE_ACCESS_TOKEN=${{ secrets.AIRTABLE_ACCESS_TOKEN }} \
              -e RR_AIRTABLE_ACCESS_TOKEN=${{ secrets.AIRTABLE_ACCESS_TOKEN }} \
              -e KEYSTORE_PASSWORD=${{ secrets.KEYSTORE_PASSWORD }} \
              -v /etc/regelrett/keystore/keystore.jks:/etc/regelrett/keystore/keystore.jks:ro \
              '${{ env.IMAGE_URL }}'
          "


  deploy-dev:
    name: Deploy to dev
    if: github.ref == 'refs/heads/main'
    needs: [ build, deploy-gcp, pharos ]
    runs-on: ubuntu-latest
    environment:
      name: dev
    permissions:
      id-token: write
    steps:
      - uses: octo-sts/action@6177b4481c00308b3839969c3eca88c96a91775f # v1.0.0
        id: octo-sts
        with:
          scope: kartverket/skvis-apps
          identity: regelrett
      - name: Checkout skvis-apps
        uses: actions/checkout@v4
        with:
          repository: kartverket/skvis-apps
          ref: main
          token: ${{ steps.octo-sts.outputs.token }}
      - name: Update version
        run: |
          echo "\"${{ needs.build.outputs.image_url }}\"" > "env/atgcp1-dev/regelrett-main/${{ env.ARGO_VERSION_FILE }}"
          git config --global user.email "noreply@kartverket.no"
          git config --global user.name "Regelrett CI"
          git commit -am "Update ${{ env.ARGO_VERSION_FILE }}"
          git push
