name: was-scan.yml
on:
  workflow_dispatch:
    inputs:
      commit_sha:
        description: 'Commit hash to deploy'
        default: ''
        type: string
  pull_request:
    branches:
      - '**'
    paths:
      - compose.yaml
      - build.gradle.kts
      - src/**
      - .github/workflows/was-scan.yml
  push:
    paths:
      - compose.yaml
      - build.gradle.kts
      - src/**
      - .github/workflows/was-scan.yml
    branches:
      - '**'
permissions: read-all

env:
  REGION: europe-north1
  DB_URL: 'jdbc:postgresql://regelrett-db:5432/regelrett'
  RR_DATABASE_HOST: regelrett-db:5432
  RR_DATABASE_NAME: regelrett
  RR_SCHEMA_SIKKERHETSKONTROLLER_WEBHOOK_ID: "ach2vlnWcdxY8Cl3k"
  RR_SCHEMA_DRIFTSKONTINUITET_WEBHOOK_ID: "achCxVfK6DaWMhchX"
  RR_SERVER_ALLOWED_ORIGINS: "regelrett-frontend-1024826672490.europe-north1.run.app,*.fly.dev,localhost:5173"
  GCP_PROVIDER_URL: https://regelrett-frontend-1024826672490.europe-north1.run.app/api/callback
  FRONTEND_URL_HOST: regelrett-frontend-1024826672490.europe-north1.run.app
  SIKKERHETSKONTROLLER_WEBHOOK_ID: "ach2vlnWcdxY8Cl3k"
  DRIFTSKONTINUITET_WEBHOOK_ID: "achCxVfK6DaWMhchX"
  ALLOWED_CORS_HOSTS: "regelrett-frontend-1024826672490.europe-north1.run.app,*.fly.dev,localhost:5173"
  REGISTRY: ghcr.io
  ARGO_VERSION_FILE: image-url-regelrett-backend
  BACKEND_IMAGE_NAME: ${{ github.repository }}-backend
  FRONTEND_IMAGE_NAME: ${{ github.repository }}-frontend

jobs:
  backend:
    name: Pull Backend
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:

      - name: Check out code
        uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Start docker network
        run : docker network create scan-net

      - name: Run db
        run: |
          docker run --name regelrett-db --network scan-net -it \
            -e POSTGRES_PASSWORD=pwd \
            -e POSTGRES_USER=postgres \
            -e POSTGRES_DB=regelrett \
            -p 5432:5432 -d postgres:15.4

      - name: Pull backend image
        run: docker pull ${{ env.REGISTRY }}/${{ env.BACKEND_IMAGE_NAME }}:latest

      - name: Set repository name
        run: echo "BACKEND_IMAGE_NAME=$(echo '${{ github.repository }}' | cut -d'/' -f2)-backend" >> $GITHUB_ENV


      - name: Set repository name
        run: echo "FRONTEND_IMAGE_NAME=$(echo '${{ github.repository }}' | cut -d'/' -f2)-frontend" >> $GITHUB_ENV

      - name: Run backend
        run: |
          sudo docker run -d --name '${{ env.BACKEND_IMAGE_NAME }}' --network scan-net -p 8080:8080 \
          -e RR_OAUTH_CLIENT_ID=${{ secrets.ENTRA_CLIENT_ID }} \
          -e RR_OAUTH_TENANT_ID=${{ secrets.ENTRA_TENANT_ID }} \
          -e RR_OAUTH_CLIENT_SECRET=${{ secrets.ENTRA_CLIENT_SECRET }}  \
          -e RR_OAUTH_SUPER_USER_GROUP_ID=${{secrets.SUPER_USER_GROUP_ID}} \
          -e RR_DATABASE_HOST='${{ env.RR_DATABASE_HOST }}' \
          -e RR_DATABASE_NAME='${{ env.RR_DATABASE_NAME }}' \
          -e RR_SERVER_ALLOWED_ORIGINS=${{ env.RR_SERVER_ALLOWED_ORIGINS }} \
          -e RR_SCHEMA_SIKKERHETSKONTROLLER_WEBHOOK_ID=${{ env.RR_SCHEMA_SIKKERHETSKONTROLLER_WEBHOOK_ID }} \
          -e RR_SCHEMA_DRIFTSKONTINUITET_WEBHOOK_ID=${{ env.RR_SCHEMA_DRIFTSKONTINUITET_WEBHOOK_ID }} \
          -e RR_SCHEMA_SIKKERHETSKONTROLLER_WEBHOOK_SECRET=${{ secrets.SIKKERHETSKONTROLLER_WEBHOOK_SECRET_GCP }} \
          -e RR_SCHEMA_DRIFTSKONTINUITET_WEBHOOK_SECRET=${{ secrets.DRIFTSKONTINUITET_WEBHOOK_SECRET_GCP }} \
          -e RR_SCHEMA_SIKKERHETSKONTROLLER_AIRTABLE_ACCESS_TOKEN=${{ secrets.AIRTABLE_ACCESS_TOKEN }} \
          -e RR_SCHEMA_DRIFTSKONTINUITET_AIRTABLE_ACCESS_TOKEN=${{ secrets.AIRTABLE_ACCESS_TOKEN }} \
          -e RR_AIRTABLE_ACCESS_TOKEN=${{ secrets.AIRTABLE_ACCESS_TOKEN }} \
          -e AIRTABLE_ACCESS_TOKEN=${{ secrets.AIRTABLE_ACCESS_TOKEN }} \
          -e CLIENT_ID=${{ secrets.ENTRA_CLIENT_ID }} \
          -e TENANT_ID=${{ secrets.ENTRA_TENANT_ID }} \
          -e CLIENT_SECRET=${{ secrets.ENTRA_CLIENT_SECRET }}  \
          -e DB_URL='${{ env.DB_URL }}' \
          -e AUTH_PROVIDER_URL=${{ env.GCP_PROVIDER_URL }} \
          -e KEYSTORE_PASSWORD=${{ secrets.KEYSTORE_PASSWORD }} \
          -e FRONTEND_URL_HOST=${{ env.FRONTEND_URL_HOST }} \
          -e SIKKERHETSKONTROLLER_WEBHOOK_ID=${{ env.SIKKERHETSKONTROLLER_WEBHOOK_ID }} \
          -e DRIFTSKONTINUITET_WEBHOOK_ID=${{ env.DRIFTSKONTINUITET_WEBHOOK_ID }} \
          -e SIKKERHETSKONTROLLER_WEBHOOK_SECRET=${{ secrets.SIKKERHETSKONTROLLER_WEBHOOK_SECRET_GCP }} \
          -e DRIFTSKONTINUITET_WEBHOOK_SECRET=${{ secrets.DRIFTSKONTINUITET_WEBHOOK_SECRET_GCP }} \
          -e ALLOWED_CORS_HOSTS=${{ env.ALLOWED_CORS_HOSTS }} \
          -e SUPER_USER_GROUP_ID=${{secrets.SUPER_USER_GROUP_ID}} \
          -v /etc/regelrett/keystore/keystore.jks:/etc/regelrett/keystore/keystore.jks:ro \
          ${{ env.REGISTRY }}/${{ env.BACKEND_IMAGE_NAME }}:latest
