### Metodeverk for deling
GET https://api.airtable.com/v0/appzJQ8Tkmm8DobrJ/tblLZbUqA0XnUgC2v
Authorization: Bearer {{AIRTABLE_TOKEN}}

###

GET https://api.airtable.com/v0/appzJQ8Tkmm8DobrJ/tblLZbUqA0XnUgC2v?offset=itrEBNYNjNHE6o6gX/recc7IE7PBvvkrcHN
Authorization: Bearer {{AIRTABLE_TOKEN}}

###

GET https://api.airtable.com/v0/appzJQ8Tkmm8DobrJ/tblLZbUqA0XnUgC2v?view=viw2XliGUJu5448Hk
Authorization: Bearer {{AIRTABLE_TOKEN}}

###

GET https://api.airtable.com/v0/appzJQ8Tkmm8DobrJ/tblLZbUqA0XnUgC2v?view=viw2XliGUJu5448Hk&
    offset=itrudhieToHuw2ZEt/recXVaggbJhBIsTTe
Authorization: Bearer {{AIRTABLE_TOKEN}}


### Hente ut informasjon fra ulike records

GET https://api.airtable.com/v0/appzJQ8Tkmm8DobrJ/tblLZbUqA0XnUgC2v/recoLfk5vlyM96vd6
Authorization: Bearer {{AIRTABLE_TOKEN}}

###

GET https://api.airtable.com/v0/appzJQ8Tkmm8DobrJ/tblLZbUqA0XnUgC2v/recdOhcX8zVd1sfZy
Authorization: Bearer {{AIRTABLE_TOKEN}}


### Alle

GET https://api.airtable.com/v0/appzJQ8Tkmm8DobrJ/tblLZbUqA0XnUgC2v?view=viw2XliGUJu5448Hk
Authorization: Bearer {{AIRTABLE_TOKEN}}

###

GET https://api.airtable.com/v0/appzJQ8Tkmm8DobrJ/tblLZbUqA0XnUgC2v?fields=ID&fields=Aktivitiet&fields=Pri&
    fields=Kortnavn
Authorization: Bearer {{AIRTABLE_TOKEN}}

###

GET https://api.airtable.com/v0/appzJQ8Tkmm8DobrJ/tblLZbUqA0XnUgC2v?view=viwCjOnfZlhMBNVJj
Authorization: Bearer {{AIRTABLE_TOKEN}}

###

GET https://api.airtable.com/v0/meta/bases/appzJQ8Tkmm8DobrJ/views
Authorization: Bearer {{AIRTABLE_TOKEN}}

###

GET https://api.airtable.com/v0/meta/bases
Authorization: Bearer {{AIRTABLE_TOKEN}}

###

GET https://api.airtable.com/v0/meta/bases/appzJQ8Tkmm8DobrJ/tables
Authorization: Bearer {{AIRTABLE_TOKEN}}

###









